### ISSUE TITLE
Wireframe for UI

### ISSUE THREAD

**Issue by simonryrie** [fac27/HearHere#2]

**Comment by simonryrie** [comment]
https://www.figma.com/file/StdQ2KMWvaH0Vwd1g5t01h/Untitled?node-id=0%3A1&t=0cVaTdUidIIlsmFv-1

**Comment by Taha-Hassan-Git** [comment]
![Image](https://user-images.githubusercontent.com/98838967/218253583-93a90594-b443-49b9-a867-6faaf73b77ec.png)
